project:
  type: website

website:
  title: "My Explorations with LLMs"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/hw-li
      - icon: mail
        href: mailto:lhaowei23@gmail.com
format:
  html:
    theme: pulse
    css: styles.css

execute:
  freeze: auto


